"""add login security fields

Revision ID: 65d192baeb3e
Revises: d2e462323c97
Create Date: 2026-03-12 09:49:04.172582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d192baeb3e'
down_revision: Union[str, Sequence[str], None] = 'd2e462323c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_policies', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'evidence', 'ai_systems', ['ai_system_id'], ['id'])
    op.create_foreign_key(None, 'evidence', 'ai_risks', ['ai_risk_id'], ['id'])
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'ai_policies', type_='foreignkey')
    # ### end Alembic commands ###
