"""initial schema

Revision ID: a97d58eca669
Revises: 
Create Date: 2026-03-03 16:15:11.528872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97d58eca669'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_policies', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'ai_risks', ['ai_risk_id'], ['id'])
    op.create_foreign_key(None, 'evidence', 'ai_systems', ['ai_system_id'], ['id'])
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'ai_policies', type_='foreignkey')
    # ### end Alembic commands ###
