"""add password_hash safely

Revision ID: d2e462323c97
Revises: a97d58eca669
Create Date: 2026-03-05 10:35:57.035019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e462323c97'
down_revision: Union[str, Sequence[str], None] = 'a97d58eca669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))

    # 2. Fill existing users with temporary value
    op.execute("UPDATE users SET password_hash = 'temporary_hash' WHERE password_hash IS NULL")

    # 3. Enforce NOT NULL constraint
    op.alter_column('users', 'password_hash', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'ai_policies', type_='foreignkey')
    # ### end Alembic commands ###
